import localFont from "next/font/local";
import Footer from "@/ui/layout/footer/Footer";
import Header from "@/ui/layout/header/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
        <Header />
        {children}
        <Footer />
    </>
  );
}
